=== eliastherkildsen/PELIOS/Resources/XML_DTD/MessageExchange.dtd
<!ELEMENT MessageExchange (Message+)>

<!ELEMENT Message (User, Text)>
<!ELEMENT User (#PCDATA)>
<!ELEMENT Text (#PCDATA)>

<!ATTLIST MessageExchange sentiment CDATA #REQUIRED>

=== eliastherkildsen/PELIOS/Resources/XML_DTD/XMLFiles/ConfusedConferenceAndBeer.xml
<?xml version="1.0"?>
<!DOCTYPE MessageExchange SYSTEM "..\MessageExchange.dtd">

<MessageExchange sentiment="Confused">
    <Message>
        <User>Frank</User>
        <Text>Hey Tommy, are you excited about the conference? I think they mentioned something about all the beer they’ll have there.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Yeah, I mean, beer is great, but did they really say how much? I thought it was more of a tech event.</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>I thought so too! But then someone mentioned a beer tasting session. Is that normal for a conference?</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>I have no idea! I’ve never been to one like that. Are we even supposed to drink that much?</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>And what about sharing a room? I’m not sure how that’ll work with all the drinking.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Right? Like, do we have to stay sober? Or just kind of keep it together? This sounds confusing.</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>Exactly! I thought sharing a room would be fun, but now I'm not so sure.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Maybe we should just stick to one beer each? Or is that even possible?</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>Who knows? Maybe we'll figure it out once we get there!</Text>
    </Message>
</MessageExchange>

=== eliastherkildsen/PELIOS/Resources/XML_DTD/XMLFiles/HopefulSQL.xml
<?xml version="1.0"?>
<!DOCTYPE MessageExchange SYSTEM "..\MessageExchange.dtd">

<MessageExchange sentiment="hopeful">
    <Message>
        <User>Frank</User>
        <Text>You know, Tommy, I'm really excited about the potential of using NoSQL for this project. It could offer a lot of flexibility, especially with the way students will be handling unstructured data.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>I see where you're coming from, Frank. But think about how structured their data could get over time. SQL could teach them a lot about relationships and normalization.</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>True, but I think we can give them a balanced challenge. Maybe we introduce NoSQL to get them thinking outside the box. They'll learn so much from building scalable, schema-less systems.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>I do think scalability is a big win, especially with larger datasets. And I guess NoSQL would be something fresh for the students to explore. Maybe this could actually open up new horizons for them.</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>Exactly! I really think this can give them more tools to work with in the future. Plus, they'll still be learning SQL down the road.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Well, if we frame it like that, I’m optimistic. They might get the best of both worlds, and we’ll still have room to integrate SQL concepts later on. I’m hopeful this could work out great.</Text>
    </Message>
</MessageExchange>

=== eliastherkildsen/PELIOS/Resources/XMLFiles/AnnoyedSnapDisc.xml
<?xml version="1.0"?>
<!DOCTYPE MessageExchange SYSTEM "MessageExchange.dtd">

<MessageExchange sentiment="annoyed">
    <Message>
        <User>Tommy</User>
        <Text>Frank, I can't believe my students are sharing code on Snapchat! What’s wrong with them?</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>Actually, Tommy, they’re using Discord for that.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Discord? No way! I swear they’re on Snapchat! This is so frustrating!</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>I promise, it’s Discord. They have channels specifically for coding discussions.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>How can they take coding seriously on Snapchat? It’s just a messaging app!</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>But they’re not using Snapchat; they’re collaborating on Discord.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>I don’t understand why they would even think Snapchat is a good idea for this!</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>It’s really Discord, Tommy. They can focus and share code properly there.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>This is just so annoying! If they’re really on Discord, why is there so much talk about Snapchat?</Text>
    </Message>
</MessageExchange>

=== eliastherkildsen/PELIOS/Resources/XMLFiles/HappySnapDisc.xml
<?xml version="1.0"?>
<!DOCTYPE MessageExchange SYSTEM "MessageExchange.dtd">

<MessageExchange sentiment="happy">
    <Message>
        <User>Tommy</User>
        <Text>Hey Frank! I just saw my students sharing code snippets on Snapchat. It's so great to see them collaborating!</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>Actually, Tommy, I think they’re using Discord for that.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Really? I thought they were all about Snapchat! It's amazing how they can use it for coding!</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>No, it’s definitely Discord. They have channels for coding discussions.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>That’s even cooler! I love how they’re making the most of Snapchat for their projects!</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>Well, they’re utilizing Discord, but I guess it’s still awesome that they’re sharing ideas!</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Exactly! Whatever platform they use, it’s great to see them engaged and excited about coding!</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>Absolutely! It’s all about the learning experience, right?</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Right! Whether it’s Snapchat or Discord, they’re doing a fantastic job!</Text>
    </Message>
</MessageExchange>

=== eliastherkildsen/PELIOS/Resources/XMLFiles/SadSQL.xml
<?xml version="1.0"?>
<!DOCTYPE MessageExchange SYSTEM "MessageExchange.dtd">

<MessageExchange sentiment="Sad">
    <Message>
        <User>Frank</User>
        <Text>Hey Tommy, I’ve been thinking about the next project, and I really wish we could use NoSQL. It feels like the right fit.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>I know, Frank. I can see why you’d want to go that route, but I’m worried that SQL is just more reliable for what we need.</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>Yeah, I get that. It’s just frustrating to see how NoSQL could really help with our unstructured data, yet it feels like we’re stuck.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>I feel the same way. It’s hard to balance my love for SQL’s structure with the potential of NoSQL. I wish we could have both.</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>Exactly. I just want our students to experience the best tools available, but I fear we’re limiting their options.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>It’s disappointing, isn’t it? I want to push boundaries too, but I worry that without SQL’s rigor, we might fail to deliver.</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>It is disappointing. I thought we’d be able to create something innovative together, but now I feel like we’re just stuck in our ways.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Yeah, it’s a bit disheartening. I want to support your vision, but I can’t shake the feeling that SQL is safer for our students.</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>I understand, Tommy. It’s just tough knowing there’s a world of possibilities out there with NoSQL, and we might miss out.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>I wish we could find a way to merge our ideas. It feels sad to think we might not come to a consensus.</Text>
    </Message>
</MessageExchange>

=== eliastherkildsen/PELIOS/Resources/XML_DTD/XMLFiles/AnnoyedSnapDisc.xml
<?xml version="1.0"?>
<!DOCTYPE MessageExchange SYSTEM "..\MessageExchange.dtd">

<MessageExchange sentiment="ANNOYED">
    <Message>
        <User>Tommy</User>
        <Text>Ugh, Frank, can you believe these students are using Snapchat to share their code? It makes no sense.</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>Tommy, they’re not using Snapchat. It’s Discord. You’ve got it wrong.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Come on, Frank, I know what I heard! Snapchat. Why would they even pick that?</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>It’s Discord, not Snapchat! You’re getting it mixed up.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Whatever. Snapchat, Discord... it’s annoying. Why do they have to keep using these random apps?</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>Because Discord’s perfect for coding. But it’s not Snapchat! Stop fixating on that.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>I’m not fixating. I just wish they used something straightforward instead of Snapchat.</Text>
    </Message>
</MessageExchange>

=== eliastherkildsen/PELIOS/Resources/XML_DTD/XMLFiles/AngryConferenceAndBeer.xml
<?xml version="1.0"?>
<!DOCTYPE MessageExchange SYSTEM "..\MessageExchange.dtd">

<MessageExchange sentiment="Angry">
    <Message>
        <User>Frank</User>
        <Text>You’ve got to be kidding me, Tommy! We’re sharing a room again? I thought we agreed on separate rooms this time!</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Hey, don’t look at me! I thought you were fine with it. Why didn’t you say anything earlier?</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>Because I didn’t think we’d have this problem again! I wanted some space this year. This is ridiculous!</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Well, it’s too late now! We’re stuck with it. What do you want me to do about it?</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>I don’t know, but this just ruins the whole trip for me. Even the beer doesn’t sound fun anymore.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Oh, come on! Don’t tell me you’re going to sulk the entire time just because we’re sharing a room. Grow up, Frank!</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>This isn’t about "sulking." I wanted a break, some space, and now it’s just a mess. I’m not looking forward to this at all anymore.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Fine! Let’s just get through the conference, have a couple of beers, and try to survive sharing the room, okay?</Text>
    </Message>
</MessageExchange>

=== eliastherkildsen/PELIOS/Resources/XMLFiles/SadSnapDisc.xml
<?xml version="1.0"?>
<!DOCTYPE MessageExchange SYSTEM "MessageExchange.dtd">

<MessageExchange sentiment="sad">
    <Message>
        <User>Tommy</User>
        <Text>Hey Frank, I just found out my students are sharing code on Snapchat. It makes me worry they’re not taking it seriously.</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>Actually, Tommy, they’re using Discord for that.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Oh, I thought it was Snapchat. I guess they prefer something so casual for their coding.</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>No, it’s really Discord. They have channels set up for their discussions.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>Still, using Snapchat feels so trivial for something as important as coding.</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>But it’s not Snapchat; they’re on Discord, where they can really focus.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>I just can’t shake the feeling that if they’re on Snapchat, they’re not really engaging with the material.</Text>
    </Message>
    <Message>
        <User>Frank</User>
        <Text>I understand your concern, but I promise they’re using Discord effectively.</Text>
    </Message>
    <Message>
        <User>Tommy</User>
        <Text>It’s just disappointing to think they might be treating it all so lightly.</Text>
    </Message>
</MessageExchange>
